### PR TITLE
Add modules_install target to the makefile

### PR DESCRIPTION
**Pull request by TSAnsari**
Signed-off-by: tansari <tansari@luxoft.com>

### CODE REVIEW

**Comment by sashko** [comment]
Titles in present simple, please

**Comment by TSAnsari** [comment]
Title changed to present simple now.

**Comment by sashko** [comment]
Adds/Add/g

**Review by frznlogic — CHANGES_REQUESTED** [review]
Why do we remove all those targets (all, clean, copy)? Install I understand why kind of, but the other ones makes sense imho?

**Comment by TSAnsari** [comment]
@frznlogic all target is not removed, clean I will add. I am not sure if there is a need for copy target when we have a target modules_install that does the install in the image? May be needed if we are manually installing on target?

**Comment by frznlogic** [comment]
@TSAnsari Yeah you're right about the all target. The copy target seems stale and weird, but the clean target would be nice IMHO. Can you re-add that?

**Comment by TSAnsari** [comment]
Done adding clean target

**Review by FlorentRevest — APPROVED** [review]

**Review by thenor — APPROVED** [review]
I had the same thought as Oscar already commented on, which is now changed, so I approve.

**Review by frznlogic — APPROVED** [review]

**Pull request merged**
