### PR TITLE
Adding copy of GPLv2

### PR DESCRIPTION
**Pull request by jeremiah**
The GPL requires that we provide a copy of the license, having a notice in the headers is not enough. This pull request merely brings in a copy of the GPLv2. :-)

### CODE REVIEW

**Comment by GordanM** [comment]
Thanks @jeremiah, I've already mentioned it to @TSAnsari that we should not miss all the guideliness! Sorry for commiting too soon!

**Comment by TSAnsari** [comment]
Sorry for not doing that and thanks Jeremiah for adding it

**Review by TSAnsari — APPROVED** [review]

**Comment by FlorentRevest** [comment]
Err, I merged it because it looked alright but it looks like it did a merge commit instead of a rebase.
I thought we had configured the repo correctly to avoid merge commits on PR...

**Comment by frznlogic** [comment]
Shit happens🙂

**Comment by GordanM** [comment]
@FlorentRevest could you please reconfigure it correctly? I think the guidline was found in Confluence but not sure if @TSAnsari followed it in the end :D

**Comment by FlorentRevest** [comment]
@GordanM I asked @TSAnsari to reconfigure this repository properly like we did on meta-arp and as far as I can see, merge commits are disabled now :)

**Comment by GordanM** [comment]
Bueno :)

**Comment by TSAnsari** [comment]
Apologies for not configuring it right the first time. But it is fixed now.

**Pull request merged**
